### ISSUE TITLE
Fix clean logic for messages older than 2 weeks

### ISSUE THREAD

**Issue by Erisa** [Yuuki-Discord/Yuuki-Bot#23]
https://discordapp.com/channels/396387695582248991/396701393945100288/669633092490887170
![image](https://user-images.githubusercontent.com/14004943/76712549-e908e280-6711-11ea-9ff2-9932e02e32a9.png)

**Comment by spotlightishere** [comment]
Will be solved by 7eea91fdd4b50c164a15073cc3c1077a28bf18c4 once merged to master.
