### ISSUE TITLE
Replace or remove cats command

### ISSUE THREAD

**Issue by spotlightishere** [Yuuki-Discord/Yuuki-Bot#28]
The backing API for the `cats` command (available at https://catfacts-api.appspot.com/api/facts for reference) is no longer available. While this has temporarily been stubbed as of bd3611a8ad073422ecda961f8c8ae10c01f0912c, it either needs a new source or to be removed entirely.

**Comment by larsenv** [comment]
Honestly I haven't worked on Yuuki and ages and I don't remember even making that command. I probably added that when I wanted to add fun commands to the bot.

I'm sure there's other cat APIs.
